catalogMode: manual
shellEmulator: true
trustPolicy: off
strictPeerDependencies: false
shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  '@uni-helper/unocss-preset-uni': true
  core-js: true
  core-js-pure: true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
