catalogMode: manual
shellEmulator: true
trustPolicy: off

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - core-js-pure
  - esbuild
  - simple-git-hooks
  - vue-demi
