/* tslint:disable */
/* eslint-disable */
/**
 * uniapp模版接口说明 - version 1.0
 *
 * uniapp模版接口说明
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface WxLoginParams {
  code: string;
}
export interface WxRequestCodeParam {
  loginCode: string;
  phoneCode: string;
}
export interface MobileLoginParam {
  /**
   * 账号注销继续登录 传1撤销注销并继续登录
   */
  cancel?: number;
  /**
   * 是否为当前手机号 1-是
   */
  currAccount?: number;
  phone: string;
  verificationCode: number;
}
export interface RefreshTokenParams {
  /**
   * token
   */
  refreshToken: string;
}
export interface Track {
  t?: number;
  type?: string;
  x?: number;
  y?: number;
}
export interface ImageCaptchaTrack {
  bgImageHeight?: number;
  bgImageWidth?: number;
  data?: object;
  endSlidingTime?: string;
  entSlidingTime?: string;
  sliderImageHeight?: number;
  sliderImageWidth?: number;
  startSlidingTime?: string;
  trackList?: Track[];
}
export interface SendSmsParam {
  /**
   * 是否为当前手机号 1-是
   */
  currAccount?: string;
  /**
   * 手机号
   */
  phone?: string;
}
export interface CaptchaRequest_SendSmsParam_ {
  /**
   * ImageCaptchaTrack
   * ---
   */
  captchaTrack: ImageCaptchaTrack;
  /**
   * SendSmsParam
   * ---
   */
  form?: SendSmsParam;
  id?: string;
}
export interface Meta {
  show?: boolean;
  title?: string;
}
export interface LoginMenuTreeNode {
  hidden?: boolean;
  id?: string;
  /**
   * Meta
   * ---
   */
  meta?: Meta;
  name?: string;
  pid?: string;
}
export interface LoginUserRole {
  dataScope?: string;
  roleId?: string;
  roleKey?: string;
  roleName?: string;
  staffId?: string;
}
export interface PmsLoginUser {
  /**
   * 账号状态
   */
  accountState?: number;
  adminType?: number;
  /**
   * 认证状态 0-未认证 1-已认证
   */
  authState?: string;
  /**
   * 账号绑定手机号
   */
  bindPhone?: string;
  /**
   * 创建时间
   */
  createTime?: string;
  /**
   * 设备id
   */
  deviceId?: string;
  /**
   * 手机号
   */
  exPhone?: string;
  /**
   * 是否有密码
   */
  hasPwd?: boolean;
  /**
   * 用户头像
   */
  headPic?: string;
  menuPermission?: LoginMenuTreeNode[];
  /**
   * 用户名称
   */
  nickName?: string;
  refreshToken?: string;
  /**
   * 注册所在地
   */
  regLocation?: string;
  rolePermission?: string[];
  roles?: LoginUserRole[];
  /**
   * 用户性别
   */
  sex?: string;
  /**
   * 修改时间
   */
  updateTime?: string;
  /**
   * 用户账号
   */
  userAccount?: string;
  /**
   * 用户id
   */
  userId?: string;
  /**
   * 用户姓名
   */
  userName?: string;
}
export interface ResultObj_PmsLoginUser_ {
  /**
   * PmsLoginUser
   * ---
   */
  data?: PmsLoginUser;
  /**
   * 响应消息
   */
  msg?: string;
  /**
   * 状态 200-成功，201-错误，400-参数错误
   */
  status?: number;
}
export interface OldImageCaptchaVO {
  backgroundImage?: string;
  backgroundImageHeight?: number;
  backgroundImageTag?: string;
  backgroundImageWidth?: number;
  data?: object;
  sliderImage?: string;
  sliderImageHeight?: number;
  sliderImageTag?: string;
  sliderImageWidth?: number;
  type?: string;
}
export interface CaptchaResponse_OldImageCaptchaVO_ {
  /**
   * OldImageCaptchaVO
   * ---
   */
  captcha?: OldImageCaptchaVO;
  id?: string;
}
export interface ResultObj_CaptchaResponse_OldImageCaptchaVO_ {
  /**
   * CaptchaResponse«OldImageCaptchaVO»
   * ---
   */
  data?: CaptchaResponse_OldImageCaptchaVO_;
  /**
   * 响应消息
   */
  msg?: string;
  /**
   * 状态 200-成功，201-错误，400-参数错误
   */
  status?: number;
}
export interface TokenVo {
  accessToken?: string;
  accessTokenExpire?: number;
  refreshToken?: string;
  refreshTokenExpire?: number;
}
export interface ResultObj_TokenVo_ {
  /**
   * TokenVo
   * ---
   */
  data?: TokenVo;
  /**
   * 响应消息
   */
  msg?: string;
  /**
   * 状态 200-成功，201-错误，400-参数错误
   */
  status?: number;
}
export interface ResultObj_Void_ {
  /**
   * 响应中的数据
   */
  data?: object;
  /**
   * 响应消息
   */
  msg?: string;
  /**
   * 状态 200-成功，201-错误，400-参数错误
   */
  status?: number;
}
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 获取当前登录用户信息
       *
       * **path:** /getLoginUser
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] PmsLoginUser
       *   data?: {
       *     // 账号状态
       *     accountState?: number
       *     adminType?: number
       *     // 认证状态 0-未认证 1-已认证
       *     authState?: string
       *     // 账号绑定手机号
       *     bindPhone?: string
       *     // 创建时间
       *     createTime?: string
       *     // 设备id
       *     deviceId?: string
       *     // 手机号
       *     exPhone?: string
       *     // 是否有密码
       *     hasPwd?: boolean
       *     // 用户头像
       *     headPic?: string
       *     // [items] start
       *     // [title] LoginMenuTreeNode
       *     // [items] end
       *     menuPermission?: Array<{
       *       hidden?: boolean
       *       id?: string
       *       // [title] Meta
       *       meta?: {
       *         show?: boolean
       *         title?: string
       *       }
       *       name?: string
       *       pid?: string
       *     }>
       *     // 用户名称
       *     nickName?: string
       *     refreshToken?: string
       *     // 注册所在地
       *     regLocation?: string
       *     // [items] start
       *     // [items] end
       *     rolePermission?: string[]
       *     // [items] start
       *     // [title] LoginUserRole
       *     // [items] end
       *     roles?: Array<{
       *       dataScope?: string
       *       roleId?: string
       *       roleKey?: string
       *       roleName?: string
       *       staffId?: string
       *     }>
       *     // 用户性别
       *     sex?: string
       *     // 修改时间
       *     updateTime?: string
       *     // 用户账号
       *     userAccount?: string
       *     // 用户id
       *     userId?: string
       *     // 用户姓名
       *     userName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      getLoginUserUsingGET<Config extends Alova2MethodConfig<ResultObj_PmsLoginUser_>>(
        config?: Config
      ): Alova2Method<ResultObj_PmsLoginUser_, 'general.getLoginUserUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 微信CODE登录
       *
       * **path:** /login/doWxLogin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] TokenVo
       *   data?: {
       *     accessToken?: string
       *     accessTokenExpire?: number
       *     refreshToken?: string
       *     refreshTokenExpire?: number
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      doWxLoginUsingPOST<
        Config extends Alova2MethodConfig<ResultObj_TokenVo_> & {
          data: WxLoginParams;
        }
      >(
        config: Config
      ): Alova2Method<ResultObj_TokenVo_, 'general.doWxLoginUsingPOST', Config>;
      /**
       * ---
       *
       * [POST] 微信登录
       *
       * **path:** /login/wxAuthorizeLoginCode
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   loginCode: string
       *   phoneCode: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] TokenVo
       *   data?: {
       *     accessToken?: string
       *     accessTokenExpire?: number
       *     refreshToken?: string
       *     refreshTokenExpire?: number
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      wxAuthorizeLoginCodeUsingPOST<
        Config extends Alova2MethodConfig<ResultObj_TokenVo_> & {
          data: WxRequestCodeParam;
        }
      >(
        config: Config
      ): Alova2Method<ResultObj_TokenVo_, 'general.wxAuthorizeLoginCodeUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 登出
       *
       * **path:** /logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      logoutUsingGET<Config extends Alova2MethodConfig<null>>(
        config?: Config
      ): Alova2Method<null, 'general.logoutUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 手机登录
       *
       * **path:** /mlogin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账号注销继续登录 传1撤销注销并继续登录
       *   cancel?: number
       *   // 是否为当前手机号 1-是
       *   currAccount?: number
       *   phone: string
       *   verificationCode: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] TokenVo
       *   data?: {
       *     accessToken?: string
       *     accessTokenExpire?: number
       *     refreshToken?: string
       *     refreshTokenExpire?: number
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      mLoginUsingPOST<
        Config extends Alova2MethodConfig<ResultObj_TokenVo_> & {
          data: MobileLoginParam;
        }
      >(
        config: Config
      ): Alova2Method<ResultObj_TokenVo_, 'general.mLoginUsingPOST', Config>;
      /**
       * ---
       *
       * [POST] 刷新token
       *
       * **path:** /refreshToken
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // token
       *   refreshToken: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] TokenVo
       *   data?: {
       *     accessToken?: string
       *     accessTokenExpire?: number
       *     refreshToken?: string
       *     refreshTokenExpire?: number
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      refreshTokenUsingPOST<
        Config extends Alova2MethodConfig<ResultObj_TokenVo_> & {
          data: RefreshTokenParams;
        }
      >(
        config: Config
      ): Alova2Method<ResultObj_TokenVo_, 'general.refreshTokenUsingPOST', Config>;
      /**
       * ---
       *
       * [POST] 发送验证码
       *
       * **path:** /sendSms
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // [title] ImageCaptchaTrack
       *   captchaTrack: {
       *     bgImageHeight?: number
       *     bgImageWidth?: number
       *     data?: object
       *     endSlidingTime?: string
       *     entSlidingTime?: string
       *     sliderImageHeight?: number
       *     sliderImageWidth?: number
       *     startSlidingTime?: string
       *     // [items] start
       *     // [title] Track
       *     // [items] end
       *     trackList?: Array<{
       *       t?: number
       *       type?: string
       *       x?: number
       *       y?: number
       *     }>
       *   }
       *   // [title] SendSmsParam
       *   form?: {
       *     // 是否为当前手机号 1-是
       *     currAccount?: string
       *     // 手机号
       *     phone?: string
       *   }
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应中的数据
       *   data?: object
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      sendSmsUsingPOST<
        Config extends Alova2MethodConfig<ResultObj_Void_> & {
          data: CaptchaRequest_SendSmsParam_;
        }
      >(
        config: Config
      ): Alova2Method<ResultObj_Void_, 'general.sendSmsUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 获取滑块信息
       *
       * **path:** /sendSmsCheck
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] CaptchaResponse«OldImageCaptchaVO»
       *   data?: {
       *     // [title] OldImageCaptchaVO
       *     captcha?: {
       *       backgroundImage?: string
       *       backgroundImageHeight?: number
       *       backgroundImageTag?: string
       *       backgroundImageWidth?: number
       *       data?: object
       *       sliderImage?: string
       *       sliderImageHeight?: number
       *       sliderImageTag?: string
       *       sliderImageWidth?: number
       *       type?: string
       *     }
       *     id?: string
       *   }
       *   // 响应消息
       *   msg?: string
       *   // 状态 200-成功，201-错误，400-参数错误
       *   status?: number
       * }
       * ```
       */
      sendSmsCheckUsingGET<Config extends Alova2MethodConfig<ResultObj_CaptchaResponse_OldImageCaptchaVO_>>(
        config?: Config
      ): Alova2Method<ResultObj_CaptchaResponse_OldImageCaptchaVO_, 'general.sendSmsCheckUsingGET', Config>;
    };
  }

  var Apis: Apis;
}
